export const ROUTES = {
  home: "/",
  login: "/login",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  register: "/register",
  admin: "/admin",
  userList: "/admin/user",
  productList: "/admin/product",
  addProduct: "/admin/product/add",
  products: "/products",
  shop: "shop/products",
  dashboard: "/admin/dashboard",
  cart: "/cart",
  payment: "/payment",
  shipping: "/admin/shipping",
  chat: "/chat",
};
